"use client";

import Link from "next/link";
import { useState } from "react";
import { CheckCircle2, Copy, Printer } from "lucide-react";
import { formatToman } from "@/lib/formatters";
import { orderStatusMeta, type StoreOrderStatus } from "@/features/orders/order-presentation";

export function OrderSuccessCard({ order }: { order: { orderNumber: string; trackingCode: string | null; createdAt: string; total: number; status: StoreOrderStatus; isGuest: boolean } }) {
  const [copied, setCopied] = useState(false); const trackingCode = order.trackingCode ?? "در حال آماده‌سازی";
  const copy = async () => { if (!order.trackingCode) return; await navigator.clipboard.writeText(order.trackingCode); setCopied(true); window.setTimeout(() => setCopied(false), 2000); };
  return <section className="max-w-xl rounded-2xl border border-border bg-surface p-7 sm:p-10"><span className="mx-auto flex size-16 items-center justify-center rounded-full bg-[#eaf6ef] text-success"><CheckCircle2 className="size-8" aria-hidden="true" /></span><p className="mt-6 text-sm font-medium text-success">پرداخت آزمایشی موفق بود</p><h1 className="mt-3 text-2xl font-semibold text-foreground">سفارش شما ثبت شد</h1><div className="mt-7 rounded-2xl bg-[#faf6f3] p-5"><p className="text-sm font-medium text-foreground">کد پیگیری سفارش شما</p><p className="mt-3 break-all text-xl font-bold tracking-wider text-primary" dir="ltr">{trackingCode}</p><button type="button" onClick={() => void copy()} className="mt-4 inline-flex items-center gap-2 rounded-full bg-surface px-4 py-2 text-sm font-medium text-primary"><Copy className="size-4" />{copied ? "کد کپی شد" : "کپی کد"}</button></div><p className="mt-5 text-sm leading-7 text-muted">این کد را حتماً کپی و ذخیره کنید. پیشنهاد می‌کنیم از این صفحه اسکرین‌شات بگیرید. برای پیگیری سفارش مهمان، به این کد و شماره موبایلی که هنگام ثبت سفارش وارد کرده‌اید نیاز دارید.</p>{order.isGuest ? <p className="mt-4 rounded-xl bg-[#fff7e8] p-4 text-sm leading-7 text-[#8a5a00]">این سفارش هنوز به حساب کاربری متصل نیست. اگر کد پیگیری را از دست بدهید، بازیابی سفارش دشوار خواهد بود.</p> : null}<dl className="mt-7 grid gap-3 border-t border-border pt-5 text-sm text-right"><div className="flex justify-between gap-4"><dt className="text-muted">شماره سفارش</dt><dd dir="ltr" className="font-medium text-foreground">{order.orderNumber}</dd></div><div className="flex justify-between gap-4"><dt className="text-muted">تاریخ ثبت</dt><dd className="font-medium text-foreground">{new Intl.DateTimeFormat("fa-IR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(order.createdAt))}</dd></div><div className="flex justify-between gap-4"><dt className="text-muted">مبلغ نهایی</dt><dd className="font-medium text-foreground">{formatToman(order.total)}</dd></div><div className="flex justify-between gap-4"><dt className="text-muted">وضعیت سفارش</dt><dd className="font-medium text-foreground">{orderStatusMeta[order.status].label}</dd></div></dl><div className="mt-7 flex flex-wrap justify-center gap-3"><Link href={`/track-order?code=${encodeURIComponent(order.trackingCode ?? "")}`} className="rounded-full bg-primary px-5 py-3 text-sm font-medium text-white">پیگیری سفارش</Link><button type="button" onClick={() => window.print()} className="inline-flex items-center gap-2 rounded-full border border-border px-5 py-3 text-sm font-medium text-foreground"><Printer className="size-4" />چاپ یا ذخیره صفحه</button></div></section>;
}
